name = "tars-kanban-board"
compatibility_date = "2024-10-01"
main = "src/index.js"

[[kv_namespaces]]
binding = "TASKS_KV"
id = "ac163672c77c4c30b4536cb8d8b7938a"

[[kv_namespaces]]
binding = "SUBAGENTS_KV"
id = "1179fd59e57d45bc90d42ef2180d68b7"

[vars]
OPENCLAW_API = "https://openclaw.yourdomain.com/api"
